### ISSUE TITLE
关于页面加载的一些建议

### ISSUE THREAD

**Issue by Zao-chen** [xiaoyvyv/Bangumi-for-Android#1]
本人不太懂安卓开发，就直接说问题了。

## 问题描述
主要是页面加载速度的问题。页面中，”发现“没问题，是直接打开的。但是其他地方感觉都是在线加载的，断网了就无法显示。像是超展开这种基本上几乎全部重新加载的页面无所谓。最主要问题就是“进度管理“这种每次只是部分更新的页面，本人喜欢进度管理放开屏，每次打开都要转个2-3秒，比较影响体验。
## 相关意见
我认为完全可以先从缓存加载显示出来，然后再更新页面，使体验更加流畅。
## 版本
Bangumi-for-Android 1.0.2
android 13

**Comment by xiaoyvyv** [comment]
fixed
