### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by umeikun** [xiaoyvyv/Bangumi-for-Android#2]
一个是全屏显示有点问题，下面还有黑条
![Screenshot_2023-12-25-20-35-33-110_com xiaoyv bangumi](https://github.com/xiaoyvyv/Bangumi-for-Android/assets/88243920/04a09e79-0886-41ff-892d-c47f26e13ed7)
我的机型是k40, v14.0.7.0
第二个是一打开应用然后点击我的页面，右上角的图标会反色失败
![Screenshot_2023-12-25-20-36-12-318_com xiaoyv bangumi](https://github.com/xiaoyvyv/Bangumi-for-Android/assets/88243920/c2c2722a-bd0d-4d70-a60b-6bf6293de97b)
不太懂安卓开发，不知道好不好改，不过真的谢谢大佬做的app

**Comment by xiaoyvyv** [comment]
已处理
