### ISSUE TITLE
文字错误、UI 改进建议、密码管理器适配

### ISSUE THREAD

**Issue by SamToki** [xiaoyvyv/Bangumi-for-Android#3]
首先感谢大佬制作 app，用户体验比班固米移动版 web 页面好了不少。
首次体验了几分钟，发现几个值得改进的小问题：

### 文字错误
* 部分页面「动画」与「动漫」混淆。
* 我的 → 维基：显示「页面正在发中…」（漏字）
* 设定 → UI 配置 → 首页中间 Tab 页面：「提示」（弹窗的标题不对）

### UI 改进建议
* 字体：希望允许设定 UI 字体为系统默认字体，个人不太习惯这种有点粗的圆体字。
* 设定：设定菜单中一些选项应做成开关或者复选框的样子，而非右箭头。否则会让用户认为还有下一级菜单。

### 密码管理器适配
登录的时候发现我的密码管理器（Keepass2Android）仅帮我填充了用户名，我需要手动拷贝粘贴密码。

（Issue 发布时使用的版本为 v1.0.2）

**Comment by xiaoyvyv** [comment]
fixed
