### ISSUE TITLE
时间线无法显示完整内容

### ISSUE THREAD

**Issue by DrLatency** [xiaoyvyv/Bangumi-for-Android#4]
很多时间线上的吐槽都被“...”省略了。吐槽点开后依然不显示完整内容，而且无法复制出来查看。用户时间线上对作品的短评无法点开，并且强制跳到作品页面。
建议去除“我的收藏”页面下所有封面的暗色处理和左下角标注。
App流畅不崩溃已经是一股清流，很多交互上也有改进。大佬加油！

**Comment by xiaoyvyv** [comment]
fixed
