### ISSUE TITLE
每次重新启动app都会创建一个新的access token

### ISSUE THREAD

**Issue by track23** [xiaoyvyv/Bangumi-for-Android#5]
1.每次重新启动app都会创建一个新的access token
2.app配色在led屏幕下偏紫（能否让用户自定义）
3.导航还是点击切换更好，滑动容易误触（下拉了很多页，一个误触就切到其他栏目去了）

**Comment by xiaoyvyv** [comment]
我看了一下确实有重复创建Acces Token的BUG，下个版本修复。

想快速清理掉之前创建的 Token，可以打开 https://next.bgm.tv/demo/access-token 页面，按 F12 打开控制台，在控制台TAB内输入下面的代码，刷新网页即可全部清理掉。

```javascript
document.querySelectorAll("button").forEach(item => item.onclick());
```

**Comment by xiaoyvyv** [comment]
已修复：[https://github.com/xiaoyvyv/Bangumi-for-Android/commit/b292a5bd274d603876f146c1cfdafd40e536f143](https://github.com/xiaoyvyv/Bangumi-for-Android/commit/b292a5bd274d603876f146c1cfdafd40e536f143)
